title: Allyson Totpal
description: Future Data Analyst | MS in Data Science in Progress | Customer Service Pro with a Passion for Data | Python, SQL, & R
# show_downloads: true
theme: jekyll-theme-minimal
